init:
  - git config --global core.autocrlf input
build_script:
  - cmd: ./build.cmd
test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: uSluPqd+MU82TuwkJR3iZuHOzSy5HU+kQgM6O5mUF1U=
  on:
    branch: master       # remove to push symbols to SymbolSource.org
