init:
  - git config --global core.autocrlf input
build_script:
  - cmd: ./build.cmd
test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: uSluPqd+MU82TuwkJR3iZuHOzSy5HU+kQgM6O5mUF1U=
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
