init:
  - git config --global core.autocrlf input
build_script:
  - cmd: ./build.cmd
test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: QNo4JGKb51SnNDdk5vGVNkAp0sA/Or0CEX8tDe7e/fyigmUO99udtldbglogGNgU
  on:
    branch: master       # remove to push symbols to SymbolSource.org
