init:
  - git config --global core.autocrlf input
build_script:
  - cmd: ./build.cmd
test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
deploy:
- provider: NuGet
  on:
    branch: master       # remove to push symbols to SymbolSource.org
- provider: NuGet
  on:
    appveyor_repo_tag: true
