init:
  - git config --global core.autocrlf input
build_script:
  - cmd: ./build.cmd
test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: 36uca7cn87q4jnsxiphwrm8v
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
