// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("System.Functional")]
[assembly: AssemblyProductAttribute("System.Functional")]
[assembly: AssemblyDescriptionAttribute("System.Functional is a minimum extension library to write more readable functional code in C#.")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "System.Functional";
        internal const System.String AssemblyProduct = "System.Functional";
        internal const System.String AssemblyDescription = "System.Functional is a minimum extension library to write more readable functional code in C#.";
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
    }
}
